name: ai
channels:
  - https://conda.anaconda.org/trung # multiprocessing-logging, pysoundfile, sidekit
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/numba # numba
  - https://conda.anaconda.org/r # r
  - defaults
dependencies:
  - python=3.5
  - Cython
  - pillow
  - toolz
  - psutil

  # scienctific computing
  - numpy=1.13.3
  - scipy=0.19.1
  - matplotlib
  - seaborn # visualization
  - pandas
  - sympy
  - nose
  - numba
  - nltk
  - spacy

  # interactive ipython and notebook
  - ipython
  - jupyter
  - ipywidgets=5.2.2

  # graphic processing
  - opencv
  - scikit-learn

  # data mining
  - Scrapy
  - wikipedia
  - guppy # for reddit
  - html5lib

  # data management
  - h5py # create dataset
  - pytables
  - pymongo
  - pyyaml
  - lxml
  - openpyxl # read excel
  - xlwt # create excel

  # network
  - paramiko #library for read remote file ssh
  - pycrypto
  - requests
  - Django

  # others
  - numexpr
  - colorama
  - six
  - memory_profiler=0.47
  - sidekit
  - resampy

  # python docs
  - Sphinx

  - pip:
    - notedown #convert markdown to ipynb
    - soundfile # read sph audio file python
    - librosa
    - twython # for twitter
    - vk # for vk
    - facebook-sdk # facebook
    - praw # for reddit
    - pysptk
    - tensorflow-gpu
