#################################################################
# Note: you have to build h5py-mpi yourself
# 		if you want none mpi verstion add this to dependencies: - h5py=2.5.0
#		openmpi is built with macport gcc-4.9.3
#
# * Download openmpi-1.10.1 source code
# 		cd openmpi-1.10.1
# 		./configure --prefix=/Users/trungnt13/libs/openmpi
# 		make all
# 		make install
#		export PATH=/Users/trungnt13/libs/openmpi/bin:$PATH
#		export DYLD_LIBRARY_PATH=/Users/trungnt13/libs/openmpi/lib:$DYLD_LIBRARY_PATH
#		export CPPFLAGS=-I/Users/trungnt13/libs/openmpi/include
#
# * Download hdf5 source, then build hdf5-parrallel:
# 		export CC=/Users/trungnt13/libs/openmpi/bin/mpicc
# 		./configure --prefix=/Users/trungnt13/libs/hdf5-par --enable-parallel --enable-shared
# 		make
# 		make check
# 		make install
#		export PATH=/Users/trungnt13/libs/hdf5-par/bin:$PATH
#		export DYLD_LIBRARY_PATH=/Users/trungnt13/libs/hdf5-par/lib:$DYLD_LIBRARY_PATH
#		export CPPFLAGS=-I/Users/trungnt13/libs/hdf5-par/include
#
# * source activate ai
# * pip install mpi4py
# * Git clone h5py, then build h5py:
# 		export CC=/Users/trungnt13/libs/openmpi/bin/mpicc
#		python setup.py configure --mpi --hdf5=/Users/trungnt13/libs/hdf5-par
#		python setup.py build
#		python setup.py install
#
# pydot require graphviz, install graphviz with mac ports first
#################################################################


name: ai
channels:
  - https://conda.anaconda.org/trung # multiprocessing-logging, pysoundfile, sidekit
  - https://conda.anaconda.org/numba # numba
  - https://conda.anaconda.org/intel # intel
  - https://conda.anaconda.org/conda-forge
  - defaults
dependencies:
  - python=2.7
  - Cython
  - pillow
  - toolz
  - psutil
  # - tcl/tk

  # scienctific computing
  - numpy=1.11.1
  - scipy=0.17.1
  - matplotlib
  - vispy # visualization
  - seaborn # visualization
  - pandas
  - sympy
  - nose
  - numba
  - graphviz # for computation graph visualization
  - pydot2 # for computation graph visualization
  - nltk

  # interactive ipython and notebook
  - ipython
  - jupyter
  - notedown #convert markdown to ipynb
  - ipywidget>=5.2.2

  # speech processing
  - libsamplerate
  - pysoundfile # read sph audio file python

  # graphic processing
  - opencv

  # deep learning api
  # - pycuda
  - pygpu
  - theano
  - pymc

  # data science tools
  - pymc
  - scikit-learn

  # data mining
  - Scrapy
  - praw # for reddit
  - wikipedia
  - guppy # for reddit
  - html5lib
  - html2text

  # data management
  - h5py=2.5.0 # create dataset
  - pytables
  - pymongo
  - mongoengine
  - pyyaml
  - lxml
  - openpyxl # read excel
  - xlwt # create excel

  # network
  - paramiko #library for read remote file ssh
  - pycrypto
  - requests
  - multiprocessing-logging
  - progressbar
  - Django

  # others
  # - image
  - numexpr
  - colorama
  - six
  - memory_profiler=0.41
  - sidekit

  - pip:
    - scikits.samplerate
    - git+https://github.com/trungnt13/pyslurm.git#egg=pyslurm
    - pyparsing==1.5.7
    - pydot==1.0.28