#################################################################
# Note: you have to build h5py-mpi yourself
# 		if you want none mpi verstion add this to dependencies: - h5py=2.5.0
#
# * First, make sure you have openmpi and mpicc in your path
#
# * Download hdf5 source, then build hdf5-parrallel
# 		export CC=/gcc/4.9.1/bin/mpicc
# 		./configure --prefix=/path/to/parallel/hdf5 --enable-parallel --enable-shared
# 		make
# 		make check
# 		make install
#
# * source activate ai
# * pip install mpi4py
# * Git clone h5py, then build h5py:
# 		export CC=/gcc/4.9.1/bin/mpicc
#		python setup.py configure --mpi --hdf5=/path/to/parallel/hdf5
#		python setup.py build
#		python setup.py install
#################################################################

name: ai
channels:
  - https://conda.anaconda.org/trung # multiprocessing-logging, pysoundfile, sidekit
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/numba # numba
  - defaults
dependencies:
  - python=2.7
  - Cython
  - pillow
  - toolz
  - psutil
  # - tcl/tk

  # scienctific computing
  - numpy=1.11.1
  - scipy=0.17.1
  - matplotlib
  - vispy # visualization
  - seaborn # visualization
  - pandas
  - sympy
  - nose
  - numba
  - nltk

  # interactive ipython and notebook
  - ipython
  - jupyter
  - notedown #convert markdown to ipynb
  - ipywidget=5.2.2

  # speech processing
  - libsamplerate
  - pysoundfile # read sph audio file python

  # graphic processing
  - opencv

  # deep learning api
  # - pycuda
  - pygpu
  - theano
  - pymc

  # data science tools
  - pymc
  - scikit-learn

  # data mining
  - Scrapy
  - praw # for reddit
  - wikipedia
  - guppy # for reddit
  - html5lib
  - html2text

  # data management
  - h5py=2.5.0 # create dataset
  - pytables
  - pymongo
  - mongoengine
  - pyyaml
  - lxml
  - openpyxl # read excel
  - xlwt # create excel

  # network
  - paramiko #library for read remote file ssh
  - pycrypto
  - requests
  - multiprocessing-logging
  - progressbar
  - Django

  # others
  # - image
  - numexpr
  - colorama
  # - tkinter
  # - readchar
  - six
  - sidekit

  - memory_profiler=0.41

  - pip:
    - scikits.samplerate
    - git+https://github.com/trungnt13/islurm.git#egg=islurm
    - pyparsing==1.5.7
    - pydot==1.0.28